# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on:
  push:
    branches: [ "action" ]
  pull_request:
    branches: [ "action" ]

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 1.8
      uses: actions/setup-java@v3
      with:
        java-version: '8.0'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: |  
           echo "Check Two"
           mvn clean test '-Dcucumber.filter.tags= @s1' -Dcucumber.execution.parallel.config.strategy=fixed  -Dcucumber.execution.parallel.enabled=true-Dcucumber.execution.parallel.config.fixed.parallelism=1  -Dcucumber.glue=com.nisum.api -DtestType=api -Dcucumber.features=features/api/  -Dcucumber.plugin=pretty  -Dcucumber.plugin=html:target/cucumber.html 
    
    - name: Show cucumber json path
      run: cd target && ls
    - name: Post data to elastic search
      run: |
           cd target && curl -k --location --request POST 'https://qa-tap.mynisum.com:8083/GithubBranchesApp/post-circleci-actions' --header 'accept: */*' --form 'file=@"cucumber.json"' --form 'attachment=""' --form 'project="cirlcecitest123"' --form 'buildDate="1675862305125"' --form 'buildNumber="1"'
   
      
    # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
    - name: Update dependency graph
      uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
